routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('welcome');
});

Auth::routes();


Route::get('/customer', 'FrontEndController@index')->name('front.index');


Route::get('/home', 'HomeController@index')->name('home');
Route::get('profile', 'HomeController@profile')->name('profile');
Route::match(['get', 'post'], 'profile-setting', 'HomeController@profileEdit')->name('profile.setting');
Route::get('profile-inactive', 'HomeController@inactive')->name('profile.inactive');
Route::get('profile-delete', 'HomeController@delete')->name('profile.delete');
Route::post('change-password', 'HomeController@changePassword')->name('change-password');

Route::get('categories/{id}/delete', 'CategoryController@delete')->name('categories.delete');
Route::get('categories/trash', 'CategoryController@trash')->name('categories.trash');
Route::get('categories/{id}/restore', 'CategoryController@restore')->name('categories.restore');
Route::get('categories/{id}/delete-permanent', 'CategoryController@deletePermanent')->name('categories.delete.permanent');
Route::resource('categories', 'CategoryController');

Route::get('products/{id}/delete', 'ProductController@delete')->name('products.delete');
Route::get('products/trash', 'ProductController@trash')->name('products.trash');
Route::get('products/{id}/restore', 'ProductController@restore')->name('products.restore');
Route::get('products/{id}/delete-permanent', 'ProductController@deletePermanent')->name('products.delete.permanent');
Route::get('products/{slug}/download-image', 'ProductController@downloadImage')->name('products.download.image');
Route::resource('products', 'ProductController');

Route::group(['prefix' => 'users'], function () {
    Route::get('administrator', 'UserController@administratorIndex')->name('user.administrator.index');
    Route::get('administrator/create', 'UserController@administratorCreate')->name('user.administrator.create');
    Route::post('administrator', 'UserController@administratorStore')->name('user.administrator.store');
    Route::get('administrator/{id}', 'UserController@administratorShow')->name('user.administrator.show');
    Route::get('administrator/{id}/edit', 'UserController@administratorEdit')->name('user.administrator.edit');
    Route::match(['put', 'patch'], 'administrator/{id}', 'UserController@administratorUpdate')->name('user.administrator.update');
    Route::get('administrator/{id}/delete', 'UserController@administratorDelete')->name('user.administrator.delete');

    Route::get('supplier', 'UserController@supplierIndex')->name('user.supplier.index');
    Route::get('supplier/create', 'UserController@supplierCreate')->name('user.supplier.create');
    Route::post('supplier', 'UserController@supplierStore')->name('user.supplier.store');
    Route::get('supplier/{id}', 'UserController@supplierShow')->name('user.supplier.show');
    Route::get('supplier/{id}/edit', 'UserController@supplierEdit')->name('user.supplier.edit');
    Route::match(['put', 'patch'], 'supplier/{id}', 'UserController@supplierUpdate')->name('user.supplier.update');
    Route::get('supplier/{id}/delete', 'UserController@supplierDelete')->name('user.supplier.delete');

    Route::get('customer', 'UserController@customerIndex')->name('user.customer.index');
    Route::get('customer/create', 'UserController@customerCreate')->name('user.customer.create');
    Route::post('customer', 'UserController@customerStore')->name('user.customer.store');
    Route::get('customer/{id}', 'UserController@customerShow')->name('user.customer.show');
    Route::get('customer/{id}/edit', 'UserController@customerEdit')->name('user.customer.edit');
    Route::match(['put', 'patch'], 'customer/{id}', 'UserController@customerUpdate')->name('user.customer.update');
    Route::get('customer/{id}/delete', 'UserController@customerDelete')->name('user.customer.delete');
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use SoftDeletes;

    protected $guarded = [];

    public function category()
    {
        return $this->belongsTo('App\Category', 'id');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Product;
use App\User;
use Illuminate\Http\Request;
use Intervention\Image\Facades\Image;
use Illuminate\Support\Carbon;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Gate;

class ProductController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $this->authorize('admin_supplier');

        // if (Gate::allows('admin')) {
        if (request()->ajax()) {
            return datatables()->of(Product::with(['category'])->get())
                ->editColumn('categoryID', function ($request) {
                    return $request->category->name;
                })
                ->editColumn('price', function ($request) {
                    return 'IDR ' . number_format($request->price, 2);
                })
                ->addColumn('action', function ($request) {
                    return view('admin.products.action', [
                        'request' => $request,
                        'url_show' => route('products.show', Crypt::encrypt($request->id)),
                        'url_edit' => route('products.edit', Crypt::encrypt($request->id)),
                        'url_delete' => route('products.delete', Crypt::encrypt($request->id)),
                    ]);
                })
                ->addIndexColumn()
                ->rawColumns(['action'])
                ->make(true);
        }
        // }

        // if (Gate::allows('supplier')) {
        //     if (request()->ajax()) {
        //         return datatables()->of(Product::where('created_by', auth()->user()->id))
        //             ->editColumn('categoryID', function ($request) {
        //                 $category = Category::where('id', $request->categoryID)->first();
        //                 return $category->name;
        //             })
        //             ->editColumn('price', function ($request) {
        //                 return 'IDR ' . number_format($request->price, 2);
        //             })
        //             ->addColumn('action', function ($request) {
        //                 return view('admin.products.action', [
        //                     'request' => $request,
        //                     'url_show' => route('products.show', Crypt::encrypt($request->id)),
        //                     'url_edit' => route('products.edit', Crypt::encrypt($request->id)),
        //                     'url_delete' => route('products.delete', Crypt::encrypt($request->id)),
        //                 ]);
        //             })
        //             ->addIndexColumn()
        //             ->rawColumns(['action'])
        //             ->make(true);
        //     }
        // }

        return view('admin.products.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // $this->authorize('admin_supplier');

        if (Category::getChild()->count() == 0 && Category::getActive()->count() == 0) {
            toast()->error('Please added a subcategory!');
            return redirect()->back();
        }

        return view('admin.products.create', [
            'categories' => Category::getChild()->orderBy('name', 'ASC')->get()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // $this->authorize('admin_supplier');

        $product = new Product;
        $product->title = $request->get('title');
        $product->categoryID = $request->get('category');
        $product->slug = Str::slug($product->title, '-');
        $product->code = Carbon::now()->timestamp . '_' . uniqid() . '_' . rand(111111111, 999999999);
        $product->price = $request->get('price');
        $product->sku = $request->get('sku');
        $product->profit = $request->get('profit');
        $product->stock = $request->get('stock');
        $product->short_summary = $request->get('short_summary');
        $product->detail = $request->get('detail');
        $product->description = $request->get('description');
        $product->status = $request->get('status');
        $product->created_by = auth()->user()->id;

        if ($request->hasFile('images')) {
            $path_original = public_path('images/product/original/' . auth()->user()->id . '_' . auth()->user()->username . '/' . '._' . $product->code);
            $path_medium = public_path('images/product/medium/' . auth()->user()->id . '_' . auth()->user()->username . '/' . '._' . $product->code);
            $path_small = public_path('images/product/small/' . auth()->user()->id . '_' . auth()->user()->username . '/' . '._' . $product->code);

            if (!File::isDirectory($path_original) && !File::isDirectory($path_medium) && !File::isDirectory($path_small)) {
                File::makeDirectory($path_original, 0777, true, true);
                File::makeDirectory($path_medium, 0777, true, true);
                File::makeDirectory($path_small, 0777, true, true);
            }

            foreach ($request->file('images') as $image_tmp) {
                if ($image_tmp->isValid()) {
                    $extension = $image_tmp->getClientOriginalExtension();
                    $fileName = Carbon::now()->timestamp . '_' . uniqid() . '_' . $product->slug . '.' . $extension;
                    $original_image_path = $path_original . '/' . $fileName;
                    $medium_image_path = $path_medium . '/' . $fileName;
                    $small_image_path = $path_small . '/' . $fileName;

                    Image::make($image_tmp)->orientate()->save($original_image_path);
                    Image::make($image_tmp)->orientate()->resize(800, 800)->save($medium_image_path);
                    Image::make($image_tmp)->orientate()->resize(400, 400)->save($small_image_path);

                    $images[] = $fileName;
                }
            }

            $product->images = json_encode($images);
        }

        $product->save();

        toast()->success('Product : ' . $product->title . ', successfully saved.');
        return redirect()->route('products.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // $this->authorize('admin_supplier');

        $product = Product::findOrFail(Crypt::decrypt($id));
        $category = Category::where('id', $product->categoryID)->first();
        $user = User::where('id', $product->created_by)->first();
        $path_medium = 'images/product/medium/' . $user->id . '_' . $user->username . '/' . '._' . $product->code;
        return view('admin.products.show', compact('product', 'category', 'path_medium', 'user'));
    }

    public function downloadImage($slug)
    {
        // $product = Product::where('created_by', auth()->user()->id)->first();
        // if ($product->slug == $slug) {
        //     $path = asset('images/product/medium/' . auth()->user()->id . '_' . auth()->user()->username . '/' . '._' . $product->code);
        //     $images = json_decode($product->images);
        //     foreach ($images as $image) {
        //         echo ($path . '/' . $image . ' ');
        //     }
        // }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        // $this->authorize('admin_supplier');

        return view('admin.products.edit', ['product' => Product::findOrFail(Crypt::decrypt($id)), 'categories' => Category::getChild()->orderBy('name', 'ASC')->get()]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // $this->authorize('admin_supplier');

        $product = Product::findOrFail($id);
        $product->title = $request->get('title');
        $product->slug = Str::slug($product->title, '-');
        $product->categoryID = $request->get('category');
        $product->price = $request->get('price');
        $product->profit = $request->get('profit');
        $product->stock = $request->get('stock');
        $product->sku = $request->get('sku');
        $product->short_summary = $request->get('short_summary');
        $product->detail = $request->get('detail');
        $product->description = $request->get('description');
        $product->status = $request->get('status');
        $product->updated_by = auth()->user()->id;

        if ($request->hasFile('images')) {
            $path_original = public_path('images/product/original/' . auth()->user()->id . '_' . auth()->user()->username . '/' . '._' . $product->code);
            $path_medium = public_path('images/product/medium/' . auth()->user()->id . '_' . auth()->user()->username . '/' . '._' . $product->code);
            $path_small = public_path('images/product/small/' . auth()->user()->id . '_' . auth()->user()->username . '/' . '._' . $product->code);
            if (File::isDirectory($path_original) && File::isDirectory($path_medium) && File::isDirectory($path_small)) {
                File::deleteDirectory($path_original);
                File::deleteDirectory($path_medium);

resources/views/admin/products/action.blade.php
@if (request()->is('products'))
<a href="{{ $url_show }}" class="btn-sm btn-info"><i class="fa fa-eye text-inverse"></i></a>
<a href="{{ $url_edit }}" class="btn-sm btn-warning"><i class="fa fa-pencil text-inverse"></i></a>
<a href="#modalDelete" class="btn-sm btn-danger" data-toggle="modal" data-target="#modalDelete" onclick="
    $('#modalDelete #linkDelete').attr('href', '{{ $url_delete }}');
    $('#modalDelete #modalDeleteLabel').text('Are you sure?');
    $('#modalDelete #bodyDelete #deleteTitle').text('You want to moved the ');
    $('#modalDelete #bodyDelete #deleteName').text('{{ $request->title }}');
    $('#modalDelete #bodyDelete #deleteTitle1').text(' product to trash?');">
    <i class="fa fa-trash text-inverse"></i>
</a>
@endif

@if (request()->is('products/trash'))
<a href="{{ $url_restore }}" class="btn-sm btn-warning"><i class="fa fa-refresh text-inverse"></i></a>
<a href="#" class="btn-sm btn-danger" data-toggle="modal" data-target="#modalDelete" onclick="
    $('#modalDelete #linkDelete').attr('href', '{{ $url_delete_permanent }}');
    $('#modalDelete #modalDeleteLabel').text('Are you sure?');
    $('#modalDelete #bodyDelete #deleteTitle').text('You want to permanently deleted the ');
    $('#modalDelete #bodyDelete #deleteName').text('{{ $request->title }}');
    $('#modalDelete #bodyDelete #deleteTitle1').text(' product?');">
    <i class="fa fa-trash text-inverse"></i>
</a>
@endif

resources/views/admin/products/create.blade.php
@extends('layouts.app')

@section('title', 'Create Product')

@section('breadcrumb')
<li class="breadcrumb-item">Product</li>
<li class="breadcrumb-item active">Create</li>
@endsection

@push('extraCSS')
<link rel="stylesheet" type="text/css" href="{{ asset('assets/css/dropzone.css') }}">
@endpush

@push('extraJS')
<script src="{{ asset('assets/js/dropzone/dropzone.js') }}"></script>
<script src="{{ asset('assets/js/dropzone/dropzone-script.js') }}"></script>
<script src="{{ asset('assets/js/editor/ckeditor/ckeditor.js') }}"></script>
<script src="{{ asset('assets/js/editor/ckeditor/styles.js') }}"></script>
<script src="{{ asset('assets/js/editor/ckeditor/adapters/jquery.js') }}"></script>
<script type="text/javascript">
    CKEDITOR.replace( 'description', {
        on: {
            contentDom: function( evt ) {
                evt.editor.editable().on( 'contextmenu', function( contextEvent ) {
                    var path = evt.editor.elementPath();
                    if ( !path.contains( 'table' ) ) {
                        contextEvent.cancel();
                    }
                }, null, null, 5 );
            }
        }
    });

    CKEDITOR.replace( 'detail', {
        on: {
            contentDom: function( evt ) {
                evt.editor.editable().on( 'contextmenu', function( contextEvent ) {
                    var path = evt.editor.elementPath();
                    if ( !path.contains( 'table' ) ) {
                        contextEvent.cancel();
                    }
                }, null, null, 5 );
            }
        }
    });

    $(document).ready(function () {
        $('.btn-image-add').click(function() {
            var lsthtml = $('.clone').html();
            $('.increment').after(lsthtml);
        });

        $('body').on('click', '#btn-image-remove', function() {
            $(this).parents('.lst').remove();
        });
    });
</script>
@endpush

@section('content')
<!-- Container-fluid starts-->

<form method="POST" action="{{ route('products.store') }}" enctype="multipart/form-data">
    @csrf

    <div class="container-fluid">
        <div class="row product-adding">
            <div class="col-xl-6">
                <div class="card">
                    <div class="card-header">
                        <h5>Add Product</h5>
                    </div>
                    <div class="card-body">
                        <div class="digital-add needs-validation">
                            <div class="form-group">
                                <label for="title" class="col-form-label pt-0"><span>*</span> Title</label>
                                <input class="form-control" name="title" id="title" type="text" required="">
                            </div>
                            <div class="form-group">
                                <label for="sku" class="col-form-label pt-0"><span>*</span> SKU</label>
                                <input class="form-control" name="sku" id="sku" type="text" required="">
                            </div>
                            <div class="form-group">
                                <label class="col-form-label"><span>*</span> Categories</label>
                                <select class="custom-select" name="category" required="">
                                    <option>--Select--</option>
                                    @foreach ($categories as $category)
                                    <option value="{{ $category->id }}"> {{ $category->name }}
                                    </option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label class="col-form-label">Sort Summary</label>
                                <textarea class="form-control" name="short_summary" rows="7" cols="12"></textarea>
                            </div>
                            <div class="form-group">
                                <label for="stock" class="col-form-label"><span>*</span> Stock</label>
                                <input class="form-control" name="stock" id="stock" type="text" required="">
                            </div>
                            <div class="row">
                                <div class="form-group col-6">
                                    <label for="price" class="col-form-label"><span>*</span> Product
                                        Price</label>
                                    <input class="form-control" name="price" id="price" type="text" required="">
                                </div>
                                <div class="form-group col-6">
                                    <label for="profit" class="col-form-label"><span>*</span> Profit (%)</label>
                                    <input class="form-control" name="profit" id="profit" type="text" required="">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-form-label"><span>*</span> Status</label>
                                <div class="m-checkbox-inline mb-0 custom-radio-ml d-flex radio-animated">
                                    <label class="d-block" for="edo-ani">
                                        <input class="radio_animated" id="edo-ani" type="radio" name="status"
                                            value="ENABLE">
                                        Enable
                                    </label>
                                    <label class="d-block" for="edo-ani1">
                                        <input class="radio_animated" id="edo-ani1" type="radio" name="status"
                                            value="DISABLE">
                                        Disable
                                    </label>
                                </div>
                            </div>
                            <label class="col-form-label pt-0"> Product Upload</label>
                            <div class="input-group increment">
                                <input type="file" accept=".jpeg, .png, .jpg, .gif, .svg, .ico"
                                    class="myfrm form-control mr-3 pr-0" name="images[]" id="images">
                                <button class="btn btn-success btn-image-add" type="button">
                                    <i class="fa fa-plus"></i>
                                </button>
                            </div>
                            <div class="clone visible">
                                <div class="image-file control-group lst input-group mt-3">
                                    <input type="file" accept=".jpeg, .png, .jpg, .gif, .svg, .ico"
                                        class="form-control mr-3 pr-0" name="images[]" id="images-remove">
                                    <button class="btn btn-danger btn-image-remove" type="button" id="btn-image-remove">
                                        <i class="fa fa-remove"></i>
                                    </button>
                                </div>
                            </div>
                            <small class="text-muted"><i>Kosongkan jika tidak ingin mengupload gambar.</i></small>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-6">
                <div class="card">
                    <div class="card-header">
                        <h5>Add Description</h5>
                    </div>
                    <div class="card-body">
                        <div class="digital-add needs-validation">
                            <div class="form-group mb-0">
                                <div class="description-sm">
                                    <textarea id="description" name="description" cols="10" rows="4"></textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header">
                        <h5>Add Detail</h5>
                    </div>
                    <div class="card-body">
                        <div class="digital-add needs-validation">
                            <div class="form-group">
                                <textarea id="detail" name="detail" rows="4" cols="12"></textarea>
                            </div>
                            <div class="form-group mb-0">
                                <div class="product-buttons">
                                    <a href="{{ route('products.index') }}" class="btn btn-light"><i
                                            class="fa fa-arrow-left"></i>
                                        Back</a>
                                    <button type="submit" class="btn btn-primary float-right"><i
                                            class="fa fa-check"></i>
                                        Save</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</form>
<!-- Container-fluid Ends-->

@endsection

resources/views/admin/products/index.blade.php
@extends('layouts.app')

@section('title', 'Manage Products')

@section('breadcrumb')
<li class="breadcrumb-item active">Products</li>
@endsection

@push('extraCSS')
<link href="{{ asset('datatables/css/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
<link href="{{ asset('datatables/css/buttons.bootstrap4.min.css') }}" rel="stylesheet">
@endpush

@push('extraJS')
<script src="{{ asset('datatables/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('datatables/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('datatables/js/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('datatables/js/buttons.bootstrap4.min.js') }}"></script>

<script>
    $(document).ready(function(){
        $('#datatable').DataTable({
            processing: true,
            serverSide: true,
            responsive: true,
            ajax: "{{ route('products.index') }}",
            columns: [
                {data: 'DT_RowIndex'},
                {data: 'sku'},
                {data: 'title'},
                {data: 'categoryID'},
                {data: 'price'},
                {data: 'stock'},
                {
                    data: 'status',
                    render: function (data, type, full, meta)
                    {
                        if (data == "DISABLE") {
                        return '<span class="badge badge-danger">'+ data +'</span>';
                        } else {
                        return '<span class="badge badge-success">'+ data +'</span>';
                        }
                    }
                },
                {data: 'action', orderable: false, searchable: false},
            ]
        });
    });
</script>
@endpush

@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h5>Manage Products</h5>
                    <a href="{{ route('products.create') }}" class="btn btn-sm btn-primary float-right"><i
                            class="fa fa-plus"></i> Add
                        Product</a>
                    <a href="{{ route('products.trash') }}" class="btn btn-sm btn-danger float-right mr-3"><i
                            class="fa fa-recycle"></i>
                        Trash Product</a>
                    <button type="button" onclick="$('#datatable').DataTable().ajax.reload();"
                        class="btn btn-sm btn-success float-right mr-3"><i class="fa fa-refresh"></i>
                        Refresh</button>
                </div>

                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered table-striped" id="datatable">
                            <thead>
                                <tr>
                                    <th width="35">No</th>
                                    <th>SKU</th>
                                    <th>Name</th>
                                    <th>Category</th>
                                    <th>Price</th>
                                    <th>Stock</th>
                                    <th>Status</th>
                                    <th width="95" align="center">Action</th>
                                </tr>
                            </thead>
                        </table>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection