routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('welcome');
});

Auth::routes();


Route::get('/customer', 'FrontEndController@index')->name('front.index');


Route::get('/home', 'HomeController@index')->name('home');
Route::get('profile', 'HomeController@profile')->name('profile');
Route::match(['get', 'post'], 'profile-setting', 'HomeController@profileEdit')->name('profile.setting');
Route::get('profile-inactive', 'HomeController@inactive')->name('profile.inactive');
Route::get('profile-delete', 'HomeController@delete')->name('profile.delete');
Route::post('change-password', 'HomeController@changePassword')->name('change-password');

Route::get('categories/{id}/delete', 'CategoryController@delete')->name('categories.delete');
Route::get('categories/trash', 'CategoryController@trash')->name('categories.trash');
Route::get('categories/{id}/restore', 'CategoryController@restore')->name('categories.restore');
Route::get('categories/{id}/delete-permanent', 'CategoryController@deletePermanent')->name('categories.delete.permanent');
Route::resource('categories', 'CategoryController');

Route::get('products/{id}/delete', 'ProductController@delete')->name('products.delete');
Route::get('products/trash', 'ProductController@trash')->name('products.trash');
Route::get('products/{id}/restore', 'ProductController@restore')->name('products.restore');
Route::get('products/{id}/delete-permanent', 'ProductController@deletePermanent')->name('products.delete.permanent');
Route::get('products/{slug}/download-image', 'ProductController@downloadImage')->name('products.download.image');
Route::resource('products', 'ProductController');

Route::group(['prefix' => 'users'], function () {
    Route::get('administrator', 'UserController@administratorIndex')->name('user.administrator.index');
    Route::get('administrator/create', 'UserController@administratorCreate')->name('user.administrator.create');
    Route::post('administrator', 'UserController@administratorStore')->name('user.administrator.store');
    Route::get('administrator/{id}', 'UserController@administratorShow')->name('user.administrator.show');
    Route::get('administrator/{id}/edit', 'UserController@administratorEdit')->name('user.administrator.edit');
    Route::match(['put', 'patch'], 'administrator/{id}', 'UserController@administratorUpdate')->name('user.administrator.update');
    Route::get('administrator/{id}/delete', 'UserController@administratorDelete')->name('user.administrator.delete');

    Route::get('supplier', 'UserController@supplierIndex')->name('user.supplier.index');
    Route::get('supplier/create', 'UserController@supplierCreate')->name('user.supplier.create');
    Route::post('supplier', 'UserController@supplierStore')->name('user.supplier.store');
    Route::get('supplier/{id}', 'UserController@supplierShow')->name('user.supplier.show');
    Route::get('supplier/{id}/edit', 'UserController@supplierEdit')->name('user.supplier.edit');
    Route::match(['put', 'patch'], 'supplier/{id}', 'UserController@supplierUpdate')->name('user.supplier.update');
    Route::get('supplier/{id}/delete', 'UserController@supplierDelete')->name('user.supplier.delete');

    Route::get('customer', 'UserController@customerIndex')->name('user.customer.index');
    Route::get('customer/create', 'UserController@customerCreate')->name('user.customer.create');
    Route::post('customer', 'UserController@customerStore')->name('user.customer.store');
    Route::get('customer/{id}', 'UserController@customerShow')->name('user.customer.show');
    Route::get('customer/{id}/edit', 'UserController@customerEdit')->name('user.customer.edit');
    Route::match(['put', 'patch'], 'customer/{id}', 'UserController@customerUpdate')->name('user.customer.update');
    Route::get('customer/{id}/delete', 'UserController@customerDelete')->name('user.customer.delete');
});

resources/views/layouts/_menu.blade.php
<ul class="sidebar-menu">
    <li><a class="{{ (request()->is('home')) ? 'active' : '' }} sidebar-header" href="{{ route('home') }}"><i
                data-feather="home"></i><span>Dashboard</span></a>
    </li>
    <li><a class="{{ (request()->is('categories*')) ? 'active' : '' }} sidebar-header"
            href="{{ route('categories.index') }}"><i data-feather="clipboard"></i><span>Categories</span></a></li>
    <li><a class="{{ (request()->is('products*')) ? 'active' : '' }} sidebar-header"
            href="{{ route('products.index') }}"><i data-feather="box"></i><span>Products</span></a></li>
    <li><a class="sidebar-header" href=""><i data-feather="dollar-sign"></i><span>Sales</span><i
                class="fa fa-angle-right pull-right"></i></a>
        <ul class="sidebar-submenu">
            <li><a href="#"><i class="fa fa-circle"></i>Orders</a></li>
            <li><a href="#"><i class="fa fa-circle"></i>Transactions</a></li>
        </ul>
    </li>
    <li class="{{ (request()->is('users*')) ? 'active' : '' }}"><a
            class="{{ (request()->is('users*')) ? 'active' : '' }} sidebar-header" href=""><i
                data-feather="user-plus"></i><span>Users</span><i class="fa fa-angle-right pull-right"></i></a>
        <ul class="sidebar-submenu">
            <li><a class="{{ (request()->is('users/administrator*')) ? 'active' : '' }}"
                    href="{{ route('user.administrator.index') }}"><i class="fa fa-circle"></i>Administrators</a></li>
            <li><a class="{{ (request()->is('users/supplier*')) ? 'active' : '' }}"
                    href="{{ route('user.supplier.index') }}"><i class="fa fa-circle"></i>Suppliers</a></li>
            <li><a class="{{ (request()->is('users/customer*')) ? 'active' : '' }}"
                    href="{{ route('user.customer.index') }}"><i class="fa fa-circle"></i>Customers</a></li>
        </ul>
    </li>
    <li><a class="sidebar-header" href="#"><i data-feather="bar-chart"></i><span>Reports</span></a></li>
    <li class="{{ (request()->is('profile-setting')) ? 'active' : '' }}"><a
            class="{{ (request()->is('profile-setting')) ? 'active' : '' }} sidebar-header" href=""><i
                data-feather="settings"></i><span>Settings</span><i class="fa fa-angle-right pull-right"></i></a>
        <ul class="sidebar-submenu">
            <li><a class="{{ (request()->is('profile-setting')) ? 'active' : '' }}"
                    href="{{ route('profile.setting') }}"><i class="fa fa-circle"></i>Profile</a></li>
        </ul>
    </li>
    <li><a class="sidebar-header" href="#"><i data-feather="archive"></i><span>Invoice</span></a>
    </li>
    <li><a class="sidebar-header" href="#" data-toggle="modal" data-target="#modalLogout"><i
                data-feather="log-out"></i><span>Logout</span></a>
    </li>
</ul>

resources/views/layouts/_modals.blade.php
<!-- Modal Show-->
<div class="modal fade" id="modalShow" tabindex="-1" role="dialog" aria-labelledby="modalShowLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalShowLabel"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="bodyShow">
                <img class="categoryImage img-thumbnail mx-auto d-block" align="center"
                    src="{{ url('/images/user/avatar.png') }}" alt="category" width="150px">
                <div class="form-gruop row mt-3">
                    <label class="offset-2 col-3"> Name</label>
                    <label class="categoryName col-7"></label>
                </div>
                <div class="form-gruop row">
                    <label class="offset-2 col-3"> Slug</label>
                    <label class="categorySlug col-7"></label>
                </div>
                <div class="form-gruop row">
                    <label class="offset-2 col-3"> Parent</label>
                    <label class="categoryParent col-7"></label>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal"><i class="fa fa-remove"></i>
                    Close</button>
            </div>
        </div>
    </div>
</div>

<!-- Modal Delete-->
<div class="modal fade" id="modalDelete" tabindex="-1" role="dialog" aria-labelledby="modalDeleteLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalDeleteLabel">Delete Category</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="bodyDelete">
                <text id="deleteTitle"></text> <b id="deleteName"></b> <text id="deleteTitle1"></text>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal"><i class="fa fa-remove"></i>
                    Close</button>
                <a href="" class="btn btn-danger" id="linkDelete"><i class="fa fa-trash"></i> Yes</a>
            </div>
        </div>
    </div>
</div>

<!-- Modal Logout-->
<div class="modal fade" id="modalLogout" tabindex="-1" role="dialog" aria-labelledby="modalLogoutLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalLogoutLabel">Logout User</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are you sure loged out and exit system?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal"><i class="fa fa-remove"></i>
                    Close</button>
                <form action="{{ route('logout') }}" method="POST">
                    @csrf
                    <button type="submit" class="btn btn-danger"><i class="fa fa-sign-out"></i> Logout</button>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/layouts/_script.blade.php
<script src="{{ asset('assets/js/jquery-3.3.1.min.js') }}"></script>
<script src="{{ asset('assets/js/popper.min.js') }}"></script>
<script src="{{ asset('assets/js/bootstrap.js') }}"></script>
<script src="{{ asset('vendor/sweetalert2/sweetalert2.all.min.js') }}"></script>
<script src="{{ asset('assets/js/icons/feather-icon/feather.min.js') }}"></script>
<script src="{{ asset('assets/js/icons/feather-icon/feather-icon.js') }}"></script>
<script src="{{ asset('assets/js/sidebar-menu.js') }}"></script>
<script src="{{ asset('assets/js/admin-customizer.js') }}"></script>
<script src="{{ asset('assets/js/lazysizes.min.js') }}"></script>
<script src="{{ asset('assets/js/admin-script.js') }}"></script>

resources/views/layouts/_style.blade.php
<link href="https://fonts.googleapis.com/css?family=Work+Sans:100,200,300,400,500,600,700,800,900" rel="stylesheet">
<link
    href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
    rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{{ asset('assets/css/font-awesome.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('assets/css/flag-icon.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('assets/css/bootstrap.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('assets/css/admin.css') }}">

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description"
            content="Bigdeal admin is super flexible, powerful, clean &amp; modern responsive bootstrap 4 admin template with unlimited possibilities.">
        <meta name="keywords"
            content="admin template, Bigdeal admin template, dashboard template, flat admin template, responsive admin template, web app">
        <meta name="author" content="pixelstrap">
        <link rel="icon" href="{{ asset('assets/images/favicon/favicon.ico') }}" type="image/x-icon">
        <link rel="shortcut icon" href="{{ asset('assets/images/favicon/favicon.ico') }}" type="image/x-icon">
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <title>{{ config('app.name', 'Laravel') }} | @yield('title')</title>
        @include('layouts._style')
        @stack('extraCSS')
    </head>

    <body>

        <!-- page-wrapper Start-->
        <div class="page-wrapper">

            <!-- Page Header Start-->
            <div class="page-main-header">
                <div class="main-header-left">
                    <div class="logo-wrapper text-center"><a href="index.html"><img class="blur-up lazyloaded"
                                src="{{ asset('assets/images/layout-2/logo/logo.png') }}" alt=""></a></div>
                </div>
                <div class="main-header-right row">
                    <div class="mobile-sidebar">
                        <div class="media-body text-right switch-sm">
                            <label class="switch">
                                <input id="sidebar-toggle" type="checkbox" checked="checked"><span
                                    class="switch-state"></span>
                            </label>
                        </div>
                    </div>
                    <div class="nav-right col">
                        <ul class="nav-menus">
                            <li>
                                <form class="form-inline search-form">
                                    <div class="form-group">
                                        <input class="form-control-plaintext" type="search" placeholder="Search.."><span
                                            class="d-sm-none mobile-search"><i data-feather="search"></i></span>
                                    </div>
                                </form>
                            </li>
                            <li><a class="text-dark" href="#!" onclick="javascript:toggleFullScreen()"><i
                                        data-feather="maximize"></i></a></li>
                            <li class="onhover-dropdown">
                                <div class="media align-items-center"><img
                                        class="align-self-center pull-right img-50 rounded-circle blur-up lazyloaded"
                                        src="{{ asset('images/user/' . Auth::user()->avatar) }}" alt="header-user">
                                    <div class="dotted-animation"><span class="animate-circle"></span><span
                                            class="main-circle"></span></div>
                                </div>
                                <ul class="profile-dropdown onhover-show-div p-20 profile-dropdown-hover">
                                    <li><a href="{{ route('profile') }}">Profile<span class="pull-right"><i
                                                    data-feather="user"></i></span></a></li>
                                    <li><a href="{{ route('profile.setting') }}">Settings<span class="pull-right"><i
                                                    data-feather="settings"></i></span></a></li>
                                    <li><a href="#" data-toggle="modal" data-target="#modalLogout">Logout<span
                                                class="pull-right"><i data-feather="log-out"></i></span></a></li>
                                </ul>
                            </li>
                        </ul>
                        <div class="d-lg-none mobile-toggle pull-right"><i data-feather="more-horizontal"></i></div>
                    </div>
                </div>
            </div>
            <!-- Page Header Ends -->

            <!-- Page Body Start-->
            <div class="page-body-wrapper">

                <!-- Page Sidebar Start-->
                <div class="page-sidebar">
                    <div class="sidebar custom-scrollbar">
                        <div class="sidebar-user text-center">
                            <div><img class="img-60 rounded-circle lazyloaded blur-up"
                                    src="{{ asset('images/user/' . Auth::user()->avatar) }}" alt="#">
                            </div>
                            <h6 class="mt-3 f-14">{{ Auth::user()->name }}</h6>
                            <p>{{ Auth::user()->roles }}</p>
                        </div>

                        @include('layouts._menu')

                    </div>
                </div>
                <!-- Page Sidebar Ends-->

                <div class="page-body">

                    <!-- Container-fluid starts-->
                    <div class="container-fluid">
                        <div class="page-header">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="page-header-left">
                                        <h3>@yield('title')
                                            <small>Senggang | AdminPanel</small>
                                        </h3>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <ol class="breadcrumb pull-right">
                                        <li class="breadcrumb-item"><a href="{{ route('home') }}"><i
                                                    data-feather="home"></i></a>
                                        </li>
                                        @yield('breadcrumb')
                                    </ol>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Container-fluid Ends-->

                    @yield('content')

                </div>

                <!-- footer start-->
                <footer class="footer">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-6 footer-copyright">
                                <p class="mb-0">Copyright {{ date('Y') }} © Senggang.com All rights reserved.</p>
                            </div>
                            <div class="col-md-6">
                                <p class="pull-right mb-0">Hand crafted & made with<i class="fa fa-heart"></i></p>
                            </div>
                        </div>
                    </div>
                </footer>
                <!-- footer end-->

            </div>
        </div>

        @include('layouts._modals')
        @include('layouts._script')
        @include('sweetalert::alert')
        @stack('extraJS')
    </body>

</html>

resources/views/layouts/appCustomer.blade.php
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description"
            content="Bigdeal admin is super flexible, powerful, clean &amp; modern responsive bootstrap 4 admin template with unlimited possibilities.">
        <meta name="keywords"
            content="admin template, Bigdeal admin template, dashboard template, flat admin template, responsive admin template, web app">
        <meta name="author" content="pixelstrap">
        <link rel="icon" href="{{ asset('assets/images/favicon/favicon.ico') }}" type="image/x-icon">
        <link rel="shortcut icon" href="{{ asset('assets/images/favicon/favicon.ico') }}" type="image/x-icon">
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <title>{{ config('app.name', 'Laravel') }} | @yield('title')</title>
        @include('layouts._style')
        @stack('extraCSS')
    </head>

    <body>

        <!-- loader start -->
        <div class="loader-wrapper">
            <div>
                <img src="../assets/images/loader.gif" alt="loader">
            </div>
        </div>
        <!-- loader end -->

        <!-- page-wrapper Start-->
        <div class="page-wrapper">

            <!-- Page Header Start-->
            <div class="page-main-header">
                <div class="main-header-left">
                    <div class="logo-wrapper text-center"><a href="index.html"><img class="blur-up lazyloaded"
                                src="{{ asset('assets/images/layout-2/logo/logo.png') }}" alt=""></a></div>
                </div>
                <div class="main-header-right row">
                    <div class="mobile-sidebar">
                        <div class="media-body text-right switch-sm">
                            <label class="switch">
                                <input id="sidebar-toggle" type="checkbox" checked="checked"><span
                                    class="switch-state"></span>
                            </label>
                        </div>
                    </div>
                    <div class="nav-right col">
                        <ul class="nav-menus">
                            <li>
                                <form class="form-inline search-form">
                                    <div class="form-group">
                                        <input class="form-control-plaintext" type="search" placeholder="Search.."><span
                                            class="d-sm-none mobile-search"><i data-feather="search"></i></span>
                                    </div>
                                </form>
                            </li>
                            <li>
                                <a class="text-info" href="#!"> PRODUCTS</a>
                            </li>
                            <li>
                                <a class="text-info" href="#!"> CATEGORIES</a>
                            </li>
                            <li><a class="text-dark" href="#!" onclick="javascript:toggleFullScreen()"><i
                                        data-feather="maximize"></i></a></li>
                            <li><a href="#"><i class="right_side_toggle" data-feather="heart"></i><span
                                        class="dot"></span></a></li>
                            <li class="onhover-dropdown"><i data-feather="shopping-cart"></i><span
                                    class="badge badge-pill badge-primary pull-right notification-badge">3</span>
                                <ul class="notification-dropdown onhover-show-div p-0">
                                    <li>
                                        <div class="media">
                                            <div class="notification-icons bg-success mr-3"><i
                                                    data-feather="thumbs-up"></i></div>
                                            <div class="media-body">
                                                <h6 class="font-success">Someone Likes Your Posts</h6>
                                                <p class="mb-0"> 2 Hours Ago</p>
                                            </div>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="media">
                                            <div class="notification-icons bg-info mr-3"><i
                                                    data-feather="message-circle"></i></div>
                                            <div class="media-body">
                                                <h6 class="font-info">3 New Comments</h6>
                                                <p class="mb-0"> 1 Hours Ago</p>
                                            </div>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="media">
                                            <div class="notification-icons bg-secondary mr-3"><i
                                                    data-feather="download"></i></div>
                                            <div class="media-body">
                                                <h6 class="font-secondary">Download Complete</h6>
                                                <p class="mb-0"> 3 Days Ago</p>
                                            </div>
                                        </div>
                                    </li>
                                    <li class="bg-light txt-dark"><a href="#" data-original-title="" title="">All </a>
                                        notification</li>
                                </ul>
                            </li>
                        </ul>
                        <div class="d-lg-none mobile-toggle pull-right"><i data-feather="more-horizontal"></i></div>
                    </div>
                </div>
            </div>
            <!-- Page Header Ends -->

            <!-- Page Body Start-->
            <div class="page-body-wrapper">

                <!-- Page Sidebar Start-->
                <div class="page-sidebar">
                    <div class="sidebar custom-scrollbar">
                        <div class="sidebar-user text-center">
                            <div><img class="img-60 rounded-circle lazyloaded blur-up"
                                    src="{{ asset('images/user/avatar.png') }}" alt="#">
                            </div>
                            <h6 class="mt-3 f-14">Immanuel Pay</h6>
                            <p>Immanuel Pay</p>
                        </div>

                        <ul class="sidebar-menu">
                            <li><a class="{{ (request()->is('home')) ? 'active' : '' }} sidebar-header"
                                    href="{{ route('home') }}"><i data-feather="home"></i><span>Dashboard</span></a>
                            </li>
                            <li>
                                <a class="sidebar-header" href="#"><i data-feather="info"></i><span>Account
                                        Info</span></a>
                            </li>
                            <li>
                                <a class="sidebar-header" href="#"><i data-feather="map-pin"></i><span>Address
                                        Book</span></a>
                            </li>
                            <li>
                                <a class="sidebar-header" href="#"><i data-feather="shopping-bag"></i><span>My
                                        Orders</span></a>
                            </li>
                            <li>
                                <a class="sidebar-header" href="#"><i data-feather="heart"></i><span>My
                                        Wishlist</span></a>
                            </li>
                            <li>
                                <a class="sidebar-header" href="#"><i data-feather="user"></i><span>My
                                        Account</span></a>
                            </li>
                            <li>
                                <a class="sidebar-header" href="#"><i data-feather="lock"></i><span>Change
                                        Password</span></a>
                            </li>
                            <li>
                                <a class="sidebar-header" href="#" data-toggle="modal" data-target="#modalLogout"><i
                                        data-feather="log-out"></i><span>Logout</span></a>
                            </li>
                        </ul>

                    </div>
                </div>
                <!-- Page Sidebar Ends-->

                <div class="page-body">

                    <!-- Container-fluid starts-->
                    {{-- <div class="container-fluid">
                        <div class="page-header">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="page-header-left">
                                        <h3>@yield('title')
                                            <small>Senggang | AdminPanel</small>
                                        </h3>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <ol class="breadcrumb pull-right">
                                        <li class="breadcrumb-item"><a href="{{ route('home') }}"><i
                        data-feather="home"></i></a>
                    </li>
                    @yield('breadcrumb')
                    </ol>
                </div>
            </div>
        </div>
        </div> --}}
        <!-- Container-fluid Ends-->

        @yield('content')

        </div>

        <!-- footer start-->
        <footer class="footer">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-6 footer-copyright">
                        <p class="mb-0">Copyright {{ date('Y') }} © Senggang.com All rights reserved.</p>
                    </div>
                    <div class="col-md-6">
                        <p class="pull-right mb-0">Hand crafted & made with<i class="fa fa-heart"></i></p>
                    </div>
                </div>
            </div>
        </footer>
        <!-- footer end-->

        </div>
        </div>

        @include('layouts._script')
        @include('sweetalert::alert')
        @stack('extraJS')
    </body>

</html>