routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('welcome');
});

Auth::routes();


Route::get('/customer', 'FrontEndController@index')->name('front.index');


Route::get('/home', 'HomeController@index')->name('home');
Route::get('profile', 'HomeController@profile')->name('profile');
Route::match(['get', 'post'], 'profile-setting', 'HomeController@profileEdit')->name('profile.setting');
Route::get('profile-inactive', 'HomeController@inactive')->name('profile.inactive');
Route::get('profile-delete', 'HomeController@delete')->name('profile.delete');
Route::post('change-password', 'HomeController@changePassword')->name('change-password');

Route::get('categories/{id}/delete', 'CategoryController@delete')->name('categories.delete');
Route::get('categories/trash', 'CategoryController@trash')->name('categories.trash');
Route::get('categories/{id}/restore', 'CategoryController@restore')->name('categories.restore');
Route::get('categories/{id}/delete-permanent', 'CategoryController@deletePermanent')->name('categories.delete.permanent');
Route::resource('categories', 'CategoryController');

Route::get('products/{id}/delete', 'ProductController@delete')->name('products.delete');
Route::get('products/trash', 'ProductController@trash')->name('products.trash');
Route::get('products/{id}/restore', 'ProductController@restore')->name('products.restore');
Route::get('products/{id}/delete-permanent', 'ProductController@deletePermanent')->name('products.delete.permanent');
Route::get('products/{slug}/download-image', 'ProductController@downloadImage')->name('products.download.image');
Route::resource('products', 'ProductController');

Route::group(['prefix' => 'users'], function () {
    Route::get('administrator', 'UserController@administratorIndex')->name('user.administrator.index');
    Route::get('administrator/create', 'UserController@administratorCreate')->name('user.administrator.create');
    Route::post('administrator', 'UserController@administratorStore')->name('user.administrator.store');
    Route::get('administrator/{id}', 'UserController@administratorShow')->name('user.administrator.show');
    Route::get('administrator/{id}/edit', 'UserController@administratorEdit')->name('user.administrator.edit');
    Route::match(['put', 'patch'], 'administrator/{id}', 'UserController@administratorUpdate')->name('user.administrator.update');
    Route::get('administrator/{id}/delete', 'UserController@administratorDelete')->name('user.administrator.delete');

    Route::get('supplier', 'UserController@supplierIndex')->name('user.supplier.index');
    Route::get('supplier/create', 'UserController@supplierCreate')->name('user.supplier.create');
    Route::post('supplier', 'UserController@supplierStore')->name('user.supplier.store');
    Route::get('supplier/{id}', 'UserController@supplierShow')->name('user.supplier.show');
    Route::get('supplier/{id}/edit', 'UserController@supplierEdit')->name('user.supplier.edit');
    Route::match(['put', 'patch'], 'supplier/{id}', 'UserController@supplierUpdate')->name('user.supplier.update');
    Route::get('supplier/{id}/delete', 'UserController@supplierDelete')->name('user.supplier.delete');

    Route::get('customer', 'UserController@customerIndex')->name('user.customer.index');
    Route::get('customer/create', 'UserController@customerCreate')->name('user.customer.create');
    Route::post('customer', 'UserController@customerStore')->name('user.customer.store');
    Route::get('customer/{id}', 'UserController@customerShow')->name('user.customer.show');
    Route::get('customer/{id}/edit', 'UserController@customerEdit')->name('user.customer.edit');
    Route::match(['put', 'patch'], 'customer/{id}', 'UserController@customerUpdate')->name('user.customer.update');
    Route::get('customer/{id}/delete', 'UserController@customerDelete')->name('user.customer.delete');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;

class Category extends Model
{
    use SoftDeletes;

    protected $table = 'categories';

    public function parent()
    {
        return $this->belongsTo('App\Category', 'parentID', 'id');
    }

    public function child()
    {
    	return $this->hasMany('App\Category', 'parentID');
    }

    public function product()
    {
        return $this->hasMany('App\Product', 'categoryID');
    }

    public function scopeGetParent($query)
    {
    	return $this->whereNull('parentID');
    }

    public function scopeGetActive($query)
    {
    	return $this->where('status', 'ACTIVE');
    }

    public function scopeGetChild($query)
    {
        return $this->whereNotNull('parentID');
    }

    public function setSlugAttribute($value)
    {
    	$this->attributes['slug'] = Str::slug($value);
    }

    public function getNameAttribute($value)
    {
    	return ucfirst($value);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category;
use App\Product;
use Intervention\Image\Facades\Image;
use Illuminate\Support\Carbon;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Gate;

class CategoryController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $this->authorize('admin_supplier');

        if (request()->ajax()) {
            return datatables()->of(Category::all())
                ->editColumn('parentID', function ($request) {
                    if ($request->parentID == null) {
                        return '-';
                    } else {
                        return $request->parent->name;
                    }
                })
                ->addColumn('action', function ($request) {
                    return view('admin.categories.action', [
                        'request' => $request,
                        'url_edit' => route('categories.edit', Crypt::encrypt($request->id)),
                        'url_delete' => route('categories.delete', Crypt::encrypt($request->id)),
                    ]);
                })
                ->addIndexColumn()
                ->rawColumns(['action'])
                ->make(true);
        }

        return view('admin.categories.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // $this->authorize('admin');

        return view('admin.categories.create', [
            'parents' => Category::getParent()->orderBy('name', 'ASC')->get()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // $this->authorize('admin');

        $this->validate($request, [
            'name' => 'required|min:3|max:20',
            'image' => 'required|image|mimes:jpeg,png,jpg,gif,svg,ico|max:2048',
        ]);

        $category = new Category;
        $category->name = $request->get('name');
        $category->parentID = $request->get('parent');
        $category->slug = Str::slug($category->name, '-');
        $category->created_by = auth()->user()->id;

        if ($request->hasFile('image')) {
            $path_medium = public_path('images/category/medium/');
            $path_small = public_path('images/category/small/');
            if (!File::isDirectory($path_medium) && !File::isDirectory($path_small)) {
                File::makeDirectory($path_medium, 0777, true, true);
                File::makeDirectory($path_small, 0777, true, true);
            }

            $image_tmp = $request->file('image');
            if ($image_tmp->isValid()) {
                $extension = $image_tmp->getClientOriginalExtension();
                $fileName = Carbon::now()->timestamp . '_' . uniqid() . '_' . Str::slug($category->name, '-') . '.' . $extension;
                $medium_image_path = $path_medium . '/' . $fileName;
                $small_image_path = $path_small . '/' . $fileName;

                Image::make($image_tmp)->orientate()->resize(800, 800)->save($medium_image_path);
                Image::make($image_tmp)->orientate()->resize(400, 400)->save($small_image_path);

                $category->image = $fileName;
            }
        }

        $category->save();

        toast()->success('Category : ' . $category->name . ', successfully saved.');
        return redirect()->route('categories.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return Category::findOrFail(Crypt::decrypt($id));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        // $this->authorize('admin');

        return view('admin.categories.edit', [
            'category' => Category::findOrFail(Crypt::decrypt($id)),
            'parents' => Category::getParent()->orderBy('name', 'ASC')->get()
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // $this->authorize('admin');

        $category = Category::findOrFail($id);
        $category->name = $request->get('name');
        $category->parentID = $request->get('parent');
        $category->slug = Str::slug($category->name, '-');
        $category->updated_by = auth()->user()->id;

        if ($category->deleted_by != "") {
            $category->deleted_by = null;
        }

        if ($request->hasFile('image')) {
            $path_medium = public_path('images/category/medium/');
            $path_small = public_path('images/category/small/');
            if (!File::isDirectory($path_medium) && !File::isDirectory($path_small)) {
                File::makeDirectory($path_medium, 0777, true, true);
                File::makeDirectory($path_small, 0777, true, true);
            }

            if ($category->image != $request->get('image')) {
                File::delete('images/category/medium/' . $category->image);
                File::delete('images/category/small/' . $category->image);
            }

            $image_tmp = $request->file('image');
            if ($image_tmp->isValid()) {
                $extension = $image_tmp->getClientOriginalExtension();
                $fileName = Carbon::now()->timestamp . '_' . uniqid() . '_' . Str::slug($category->name, '-') . '.' . $extension;
                $medium_image_path = $path_medium . '/' . $fileName;
                $small_image_path = $path_small . '/' . $fileName;

                Image::make($image_tmp)->orientate()->resize(800, 800)->save($medium_image_path);
                Image::make($image_tmp)->orientate()->resize(400, 400)->save($small_image_path);

                $category->image = $fileName;
            }
        }

        $category->update();

        toast()->success('Category : ' . $category->name . ', successfully changed.');
        return redirect()->route('categories.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function delete($id)
    {
        // $this->authorize('admin');

        $category = Category::withCount(['child', 'product'])->find(Crypt::decrypt($id));

        if ($category->child_count == 0 && $category->product_count == 0) {
            $category->deleted_by = auth()->user()->id;
            $category->update();
            $category->delete();

            toast()->success('Category : ' . $category->name . ', successfully moved to trash.');
            return redirect()->route('categories.index');
        }

        toast()->error('Category : ' . $category->name . ', error moved to trash. This category have child or product');
        return redirect()->route('categories.index');
    }

    public function trash()
    {
        // $this->authorize('admin');

        if (request()->ajax()) {
            return datatables()->of(Category::onlyTrashed()->get())
                ->editColumn('parentID', function ($request) {
                    if ($request->parentID == null) {
                        return 'No Parent';
                    } else {
                        return $request->parent->name;
                    }
                })
                ->addColumn('action', function ($request) {
                    return view('admin.categories.action', [
                        'request' => $request,
                        'url_restore' => route('categories.restore', Crypt::encrypt($request->id)),
                        'url_delete_permanent' => route('categories.delete.permanent', Crypt::encrypt($request->id)),
                    ]);
                })
                ->addIndexColumn()
                ->rawColumns(['action'])
                ->make(true);
        }

        return view('admin.categories.trash');
    }

    public function restore($id)
    {
        // $this->authorize('admin');

        $category = Category::withTrashed()->findOrFail(Crypt::decrypt($id));
        if ($category->trashed()) {
            $category->restore();
        } else {
            toast()->error('Category : ' . $category->name . ', is not in trash.');
            return redirect()->route('categories.index');
        }

        toast()->success('Category : ' . $category->name . ', successfully restored.');
        return redirect()->route('categories.index');
    }

    public function deletePermanent($id)
    {
        // $this->authorize('admin');

        $category = Category::withTrashed()->findOrFail(Crypt::decrypt($id));
        if (!$category->trashed()) {
            toast()->error('Category : ' . $category->name . ', Can not delete permanent active category.');
            return redirect()->route('categories.index');
        } else {
            File::delete('images/category/medium/' . $category->image);
            File::delete('images/category/small/' . $category->image);
            $category->forceDelete();

            toast()->success('Category : ' . $category->name . ', permanently deleted.');
            return redirect()->route('categories.index');
        }
    }
}

resources/views/admin/categories/action.blade.php
@if (request()->is('categories'))
<a class="btn-sm btn-info mr-1" href="#modalShow" data-toggle="modal" data-target="#modalShow" onclick="
    $('#modalShow .categoryImage').attr('src', '{{ url('/images/category/medium'. '/'. $request->image) }}');
    $('#modalShow #modalShowLabel').text('Show Category : {{ $request->name }}');
    $('#modalShow #bodyShow .categoryName').text('{{ $request->name }}');
    $('#modalShow #bodyShow .categorySlug').text('{{ $request->slug }}');
    $('#modalShow #bodyShow .categoryParent').text('{{ $request->parentID == 0 ? '-' : $request->parent->name }}');">
    <i class="fa fa-eye text-inverse"></i>
</a>
<a href="{{ $url_edit }}" class="btn-sm btn-warning"><i class="fa fa-pencil text-inverse"></i></a>
<a class="btn-sm btn-danger" href="#modalDelete" data-toggle="modal" data-target="#modalDelete" onclick="
    $('#modalDelete #linkDelete').attr('href', '{{ $url_delete }}');
    $('#modalDelete #modalDeleteLabel').text('Are you sure?');
    $('#modalDelete #bodyDelete #deleteTitle').text('You want to moved the ');
    $('#modalDelete #bodyDelete #deleteName').text('{{ $request->name }}');
    $('#modalDelete #bodyDelete #deleteTitle1').text(' category to trash?');">
    <i class="fa fa-trash text-inverse"></i>
</a>
@endif

@if (request()->is('categories/trash'))
<a href="{{ $url_restore }}" class="btn-sm btn-warning"><i class="fa fa-refresh text-inverse"></i></a>
<a class="btn-sm btn-danger" href="#" data-toggle="modal" data-target="#modalDelete" onclick="
    $('#modalDelete #linkDelete').attr('href', '{{ $url_delete_permanent }}');
    $('#modalDelete #modalDeleteLabel').text('Are you sure?');
    $('#modalDelete #bodyDelete #deleteTitle').text('You want to permanently deleted the ');
    $('#modalDelete #bodyDelete #deleteName').text('{{ $request->name }}');
    $('#modalDelete #bodyDelete #deleteTitle1').text(' category?');">
    <i class="fa fa-trash text-inverse"></i>
</a>
@endif

resources/views/admin/categories/create.blade.php
@extends('layouts.app')

@section('title', 'Create Category')

@section('breadcrumb')
<li class="breadcrumb-item">Category</li>
<li class="breadcrumb-item active">Create</li>
@endsection

@push('extraCSS')
<link rel="stylesheet" type="text/css" href="{{ asset('assets/css/dropzone.css') }}}}">
@endpush

@push('extraJS')
<script src="{{ asset('assets/js/dropzone/dropzone.js') }}"></script>
<script src="{{ asset('assets/js/dropzone/dropzone-script.js') }}"></script>
@endpush

@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h5>Add Category</h5>
                    <a href="{{ route('categories.index') }}" class="btn btn-sm btn-default float-right"><i
                            class="fa fa-arrow-left"></i> Back</a>
                </div>

                <div class="card-body">
                    <form method="POST" action="{{ route('categories.store') }}" enctype="multipart/form-data">
                        @csrf
                        @method('POST')

                        <div class="row">
                            <div class="col">
                                <div class="form-group">
                                    <label for="name" class="col-form-label">Name :</label>
                                    <input type="text" class="form-control @error('name') is-invalid @enderror"
                                        value="{{ old('name') }}" name="name" id="name" required>
                                    @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="col">
                                <div class="form-group">
                                    <label for="parent" class="col-form-label">Parent :</label>
                                    <select class="form-control" name="parent" id="parent">
                                        <option value=""> No Parent</option>
                                        @foreach ($parents as $parent)
                                        <option value="{{ $parent->id }}"> -&nbsp;{{ $parent->name }}
                                        </option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-6">
                                <div class="form-group">
                                    <label for="image" class="col-form-label">Image :</label>
                                    <input type="file" accept=".jpeg, .png, .jpg, .gif, .svg, .ico"
                                        class="form-control @error('image') is-invalid @enderror"
                                        value="{{ old('image') }}" name="image" id="image">
                                    @error('image')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-success"><i class="fa fa-check"></i>
                                Save</button>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('layouts.app')

@section('title', 'Edit Category')

@section('breadcrumb')
<li class="breadcrumb-item">Category</li>
<li class="breadcrumb-item active">Edit</li>
@endsection

@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h5>Edit Category : <b> {{ $category->name }}</b></h5>
                    <a href="{{ route('categories.index') }}" class="btn btn-sm btn-default float-right"
                        id="button-back"><i class="fa fa-arrow-left"></i>
                        Back</a>
                </div>

                <div class="card-body">
                    <form method="POST" action="{{ route('categories.update', ['category' => $category->id]) }}"
                        enctype="multipart/form-data">
                        @csrf
                        @method('PUT')

                        <div class="row">
                            <div class="col">
                                <div class="form-group">
                                    <label for="name" class="col-form-label">Name :</label>
                                    <input type="text" class="form-control" value="{{ $category->name }}" name="name"
                                        id="name" required>
                                </div>
                            </div>
                            <div class="col">
                                <div class="form-group">
                                    <label for="parent" class="col-form-label">Parent :</label>
                                    <select class="form-control" name="parent" id="parent">
                                        <option value=""> No Parent</option>
                                        @foreach ($parents as $parent)
                                        <option value="{{ $parent->id }}"
                                            {{ $parent->id == $category->parentID ? 'selected' : '' }}>
                                            -&nbsp;{{ $parent->name }}
                                        </option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-6">
                                <img src="{{ asset('images/category/medium/'.$category->image) }}"
                                    class="img-thumbnail mx-auto d-block" align="center" width="120px" />
                                <div class="form-group">
                                    <label for="image" class="col-form-label">Image :</label>
                                    <input type="file" accept=".jpeg, .png, .jpg, .gif, .svg, .ico" class="form-control"
                                        value="{{ $category->image }}" name="image" id="image">
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-success"><i class="fa fa-check"></i>
                                Save</button>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/categories/index.blade.php
@extends('layouts.app')

@section('title', 'Manage Categories')

@section('breadcrumb')
<li class="breadcrumb-item active">Categories</li>
@endsection

@push('extraCSS')
<link href="{{ asset('datatables/css/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
<link href="{{ asset('datatables/css/buttons.bootstrap4.min.css') }}" rel="stylesheet">
@endpush

@push('extraJS')
<script src="{{ asset('datatables/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('datatables/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('datatables/js/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('datatables/js/buttons.bootstrap4.min.js') }}"></script>

<script>
    $(document).ready(function(){
        $('#datatable').DataTable({
            processing: true,
            serverSide: true,
            responsive: true,
            ajax: "{{ route('categories.index') }}",
            columns: [
                {data: 'DT_RowIndex'},
                {data: 'name'},
                {data: 'parentID'},
                {data: 'action', orderable: false, searchable: false},
            ]
        });
    });
</script>
@endpush

@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h5>Manage Categories</h5>
                    <a href="{{ route('categories.create') }}" class="btn btn-sm btn-primary float-right"><i
                            class="fa fa-plus"></i> Add
                        Category</a>
                    <a href="{{ route('categories.trash') }}" class="btn btn-sm btn-danger float-right mr-3"><i
                            class="fa fa-recycle"></i>
                        Trash Category</a>
                    <button type="button" onclick="$('#datatable').DataTable().ajax.reload();"
                        class="btn btn-sm btn-success float-right mr-3"><i class="fa fa-refresh"></i>
                        Refresh</button>
                </div>

                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered table-striped" id="datatable">
                            <thead>
                                <tr>
                                    <th width="35">No</th>
                                    <th>Name</th>
                                    <th>Parent</th>
                                    <th width="95" align="center">Action</th>
                                </tr>
                            </thead>
                        </table>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/categories/trash.blade.php
@extends('layouts.app')

@section('title', 'Trash Categories')

@section('breadcrumb')
<li class="breadcrumb-item">Categories</li>
<li class="breadcrumb-item active">Trash</li>
@endsection

@push('extraCSS')
<link href="{{ asset('datatables/css/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
<link href="{{ asset('datatables/css/buttons.bootstrap4.min.css') }}" rel="stylesheet">
@endpush

@push('extraJS')
<script src="{{ asset('datatables/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('datatables/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('datatables/js/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('datatables/js/buttons.bootstrap4.min.js') }}"></script>

<script>
    $(document).ready(function(){
        $('#datatable').DataTable({
            processing: true,
            serverSide: true,
            responsive: true,
            ajax: "{{ route('categories.trash') }}",
            columns: [
                {data: 'DT_RowIndex'},
                {data: 'name'},
                {data: 'parentID'},
                {data: 'action', orderable: false, searchable: false},
            ]
        });
    });
</script>
@endpush

@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h5>Trash Categories</h5>
                    <a href="{{ route('categories.index') }}" class="btn btn-sm btn-default float-right"><i
                            class="fa fa-arrow-left"></i>
                        Back</a>
                </div>

                <div class="card-body">

                    <div class="table-responsive">
                        <table class="table table-bordered table-striped" id="datatable">
                            <thead>
                                <tr>
                                    <th width="35">No</th>
                                    <th>Name</th>
                                    <th>Parent</th>
                                    <th width="58" align="center">Action</th>
                                </tr>
                            </thead>
                        </table>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection